// src/data.ts

// 1. 타입 내보내기 (export)
export type Tier = 'SSS' | 'SS' | 'S' | 'A' | 'B' | 'C' | 'D';

export interface Character {
  id: number;
  name_kor: string;
  name: string;
  tier: Tier;
  image: string;
  tags: string[];
}

// 태그 그룹
export const TAG_GROUPS = [
  {title: '모드', tags: ['사냥', '협동','보스사냥','현상금사냥꾼','일일이벤트(생존)','일일이벤트(방어)'],},
  {title: '획득조건', tags: ['게임플레이', '이벤트'],},
  {title: '각성', tags: ['1차 각성 체감↑','2차 각성 체감↑'],},
  {title: '능력', tags: ['멀티샷','멀티샷(2각)','서폿','반사'],},
];

// 2. 캐릭터 데이터 내보내기 (export)
export const characterDB: Character[] = [
  {id: 1, name_kor:"아처", name: 'elf archer', tier: "B", image: `${import.meta.env.BASE_URL}img/1_elf_archer.png`, tags: [],},
  {id: 2, name_kor:"바바", name: 'barbarian', tier: "B", image: `${import.meta.env.BASE_URL}img/2_barbarian.png`, tags: ["반사", "2차 각성 체감↑"],},
  {id: 3, name_kor:"위자드", name: 'wizard', tier: "D", image: `${import.meta.env.BASE_URL}img/3_wizard.png`, tags: [],},
  {id: 4, name_kor:"고르곤", name: 'gorgon', tier: "SSS", image: `${import.meta.env.BASE_URL}img/4_gorgon.png`, tags: ["멀티샷", "2차 각성 체감↑"],},
  {id: 5, name_kor:"엔젤", name: 'angel', tier: "C", image: `${import.meta.env.BASE_URL}img/5_angel.png`, tags: ["서폿", "2차 각성 체감↑"],},
  {id: 6, name_kor:"부두", name: 'voodoo', tier: "D", image: `${import.meta.env.BASE_URL}img/6_voodoo.png`, tags: [],},
  {id: 7, name_kor:"스퀸", name: 'spider queen', tier: "S", image: `${import.meta.env.BASE_URL}img/7_spider_queen.png`, tags: ["2차 각성 체감↑"],},
  {id: 8, name_kor:"드나", name: 'dragon knight', tier: "C", image: `${import.meta.env.BASE_URL}img/8_dragon_knight.png`, tags: ["반사"],},
  {id: 9, name_kor:"드루", name: 'druid', tier: "C", image: `${import.meta.env.BASE_URL}img/9_druid.png`, tags: ["반사"],},
  {id: 10, name_kor:"크로우", name: 'crow', tier: "B", image: `${import.meta.env.BASE_URL}img/10_crow.png`, tags: ["성소"],},
  {id: 11, name_kor:"임프", name: 'imp master', tier: "A", image: `${import.meta.env.BASE_URL}img/11_imp_master.png`, tags: ["챔피언퀘스트", "2차 각성 체감↑"],},
  {id: 12, name_kor:"프퀸", name: 'frozen queen', tier: "D", image: `${import.meta.env.BASE_URL}img/12_frozen_queen.png`, tags: [],},
  {id: 13, name_kor:"엑마", name: 'axe master', tier: "A", image: `${import.meta.env.BASE_URL}img/13_axe_master.png`, tags: ["2차 각성 체감↑"],},
  {id: 14, name_kor:"로키", name: 'rocky', tier: "D", image: `${import.meta.env.BASE_URL}img/14_rocky.png`, tags: [],},
  {id: 15, name_kor:"스나", name: 'sniper', tier: "S", image: `${import.meta.env.BASE_URL}img/15_sniper.png`, tags: ["멀티샷(2각)", "2차 각성 체감↑"],},
  {id: 16, name_kor:"후크", name: 'captain hook', tier: "A", image: `${import.meta.env.BASE_URL}img/16_captain_hook.png`, tags: ["2차 각성 체감↑"],},
  {id: 17, name_kor:"라스", name: 'lifestealer', tier: "SS", image: `${import.meta.env.BASE_URL}img/17_lifestealer.png`, tags: ["멀티샷", "반사"],},
  {id: 18, name_kor:"버서커", name: 'berserker', tier: "C", image: `${import.meta.env.BASE_URL}img/18_berserker.png`, tags: [],},
  {id: 19, name_kor:"오크", name: 'raging orc', tier: "C", image: `${import.meta.env.BASE_URL}img/19_raging_orc.png`, tags: [],},
  {id: 20, name_kor:"해적,핑해", name: 'pirate', tier: "A", image: `${import.meta.env.BASE_URL}img/20_pirate.png`, tags: ["멀티샷", "챔피언퀘스트", "2차 각성 체감↑"],},
  {id: 21, name_kor:"붐붐", name: 'boom boom', tier: "B", image: `${import.meta.env.BASE_URL}img/21_boom_boom.png`, tags: ["2차 각성 체감↑"],},
  {id: 22, name_kor:"울프", name: 'grey wolf', tier: "C", image: `${import.meta.env.BASE_URL}img/22_grey_wolf.png`, tags: ["게임플레이"],},
  {id: 23, name_kor:"롤러", name: 'roller', tier: "D", image: `${import.meta.env.BASE_URL}img/23_roller.png`, tags: ["게임플레이"],},
  {id: 24, name_kor:"킹", name: 'king', tier: "C", image: `${import.meta.env.BASE_URL}img/24_king.png`, tags: ["반사"],},
  {id: 25, name_kor:"닌자", name: 'ninja', tier: "A", image: `${import.meta.env.BASE_URL}img/25_ninja.png`, tags: ["멀티샷(2각)", "1차 각성 체감↑", "2차 각성 체감↑"],},
  {id: 26, name_kor:"엔지", name: 'engineer', tier: "C", image: `${import.meta.env.BASE_URL}img/26_engineer.png`, tags: ["반사"],},
  {id: 27, name_kor:"해머", name: 'hammerdin', tier: "C", image: `${import.meta.env.BASE_URL}img/27_hammerdin.png`, tags: [],},
  {id: 28, name_kor:"렌더멘", name: 'renderman', tier: "D", image: `${import.meta.env.BASE_URL}img/28_renderman.png`, tags: [],},
  {id: 29, name_kor:"팬텀", name: 'phantom', tier: "C", image: `${import.meta.env.BASE_URL}img/29_phantom.png`, tags: [],},
  {id: 30, name_kor:"젠틀", name: 'gentleman', tier: "A", image: `${import.meta.env.BASE_URL}img/30_gentleman.png`, tags: ["1차 각성 체감↑"],},
  {id: 31, name_kor:"블라드", name: 'vlad', tier: "C", image: `${import.meta.env.BASE_URL}img/31_vlad.png`, tags: [],},
  {id: 32, name_kor:"매닥", name: 'mad doctor', tier: "D", image: `${import.meta.env.BASE_URL}img/32_mad_doctor.png`, tags: [],},
  {id: 33, name_kor:"문어", name: 'ancient one', tier: "S", image: `${import.meta.env.BASE_URL}img/33_ancient_one.png`, tags: ["멀티샷"],},
  {id: 34, name_kor:"미노", name: 'minotaur', tier: "D", image: `${import.meta.env.BASE_URL}img/34_minotaur.png`, tags: [],},
  {id: 35, name_kor:"제우스", name: 'zeus', tier: "C", image: `${import.meta.env.BASE_URL}img/35_zeus.png`, tags: [],},
  {id: 36, name_kor:"이프", name: 'efreet', tier: "S", image: `${import.meta.env.BASE_URL}img/36_efreet.png`, tags: ["반사","1차 각성 체감↑", "2차 각성 체감↑"],},
  {id: 37, name_kor:"히드라", name: 'huntalisk', tier: "B", image: `${import.meta.env.BASE_URL}img/37_huntalisk.png`, tags: ["1차 각성 체감↑"],},
  {id: 38, name_kor:"프텍", name: 'protector', tier: "C", image: `${import.meta.env.BASE_URL}img/38_protector.png`, tags: [],},
  {id: 39, name_kor:"고릴,킹콩", name: 'ape lord', tier: "S", image: `${import.meta.env.BASE_URL}img/39_ape_lord.png`, tags: ["1차 각성 체감↑", "2차 각성 체감↑"],},
  {id: 40, name_kor:"메카", name: 'mech', tier: "A", image: `${import.meta.env.BASE_URL}img/40_mech.png`, tags: ["1차 각성 체감↑", "2차 각성 체감↑"],},
  {id: 41, name_kor:"리퍼", name: 'the ripper', tier: "A", image: `${import.meta.env.BASE_URL}img/41_the_ripper.png`, tags: ["1차 각성 체감↑","서폿"],},
  {id: 42, name_kor:"토르", name: 'thor', tier: "A", image: `${import.meta.env.BASE_URL}img/42_thor.png`, tags: ["챔피언퀘스트", "성소"],},
  {id: 43, name_kor:"프랭키", name: 'franky', tier: "SSS", image: `${import.meta.env.BASE_URL}img/43_franky.png`, tags: ["1차 각성 체감↑","이벤트"],},
  {id: 44, name_kor:"그림", name: 'grim reaper', tier: "C", image: `${import.meta.env.BASE_URL}img/44_grim_reaper.png`, tags: [],},
  {id: 45, name_kor:"눈사람", name: 'snowman', tier: "D", image: `${import.meta.env.BASE_URL}img/45_snowman.png`, tags: ["이벤트"],},
  {id: 46, name_kor:"네크", name: 'necromancer', tier: "C", image: `${import.meta.env.BASE_URL}img/46_necromancer.png`, tags: [],},
  {id: 47, name_kor:"스컬", name: 'skull master', tier: "A", image: `${import.meta.env.BASE_URL}img/47_skull_master.png`, tags: ["일일이벤트(방어)","2차 각성 체감↑"],},
  {id: 48, name_kor:"사무", name: 'samurai', tier: "A", image: `${import.meta.env.BASE_URL}img/48_samurai.png`, tags: ["성소","챌린지상점"],},
  {id: 49, name_kor:"트릭", name: 'trickster', tier: "A", image: `${import.meta.env.BASE_URL}img/49_trickster.png`, tags: ["하드코어 협동", "성소"],},
  {id: 50, name_kor:"아라", name: 'arachna', tier: "A", image: `${import.meta.env.BASE_URL}img/50_arachna.png`, tags: [],},
  {id: 51, name_kor:"버니", name: 'bunny', tier: "D", image: `${import.meta.env.BASE_URL}img/51_bunny.png`, tags: ["이벤트"],},
  {id: 52, name_kor:"프닥", name: 'plague doctor', tier: "B", image: `${import.meta.env.BASE_URL}img/52_plague_doctor.png`, tags: [],},
  {id: 53, name_kor:"보나", name: 'void knight', tier: "A", image: `${import.meta.env.BASE_URL}img/53_void_knight.png`, tags: ["서폿"],},
  {id: 54, name_kor:"허수아비", name: 'scarecrow', tier: "D", image: `${import.meta.env.BASE_URL}img/54_scarecrow.png`, tags: [],},
  {id: 55, name_kor:"비틀", name: 'beetle', tier: "A", image: `${import.meta.env.BASE_URL}img/55_beetle.png`, tags: [],},
  {id: 56, name_kor:"아누", name: 'anubis', tier: "S", image: `${import.meta.env.BASE_URL}img/56_anubis.png`, tags: ["1차 각성 체감↑"],},
  {id: 57, name_kor:"토멘", name: 'torment', tier: "S", image: `${import.meta.env.BASE_URL}img/57_torment.png`, tags: ["서폿", "게임플레이"],},
  {id: 58, name_kor:"거북", name: 'mutant turtle', tier: "SS", image: `${import.meta.env.BASE_URL}img/58_mutant_turtle.png`, tags: ["반사","성소"],},
  {id: 59, name_kor:"미라", name: 'mummy', tier: "A", image: `${import.meta.env.BASE_URL}img/59_mummy.png`, tags: ["성소"],},
  {id: 60, name_kor:"터키", name: 'turkey', tier: "D", image: `${import.meta.env.BASE_URL}img/60_turkey.png`, tags: ["이벤트"],},
  {id: 61, name_kor:"플랫", name: 'plague rat', tier: "C", image: `${import.meta.env.BASE_URL}img/61_plague_rat.png`, tags: [],},
  {id: 62, name_kor:"웨어", name: 'warebear', tier: "D", image: `${import.meta.env.BASE_URL}img/61_warebear.png`, tags: [],},
  {id: 63, name_kor:"오니", name: 'oni', tier: "C", image: `${import.meta.env.BASE_URL}img/63_oni.png`, tags: ["이벤트"],},
  {id: 64, name_kor:"고블", name: 'goblin engineer', tier: "B", image: `${import.meta.env.BASE_URL}img/64_goblin_engineer.png`, tags: ["일일이벤트(방어)"],},
  {id: 65, name_kor:"서큐", name: 'succubus', tier: "S", image: `${import.meta.env.BASE_URL}img/65_succubus.png`, tags: ["이벤트"],},
  {id: 66, name_kor:"아이비", name: 'ivy', tier: "C", image: `${import.meta.env.BASE_URL}img/66_ivy.png`, tags: [],},
  {id: 67, name_kor:"레프", name: 'leprechaun', tier: "SS", image: `${import.meta.env.BASE_URL}img/67_leprechaun.png`, tags: ["이벤트","사냥","멀티샷","반사","1차 각성 체감↑","2차 각성 체감↑"],},
  {id: 68, name_kor:"손오공", name: 'son wukong', tier: "C", image: `${import.meta.env.BASE_URL}img/68_son_wukong.png`, tags: [],},
  {id: 69, name_kor:"호플", name: 'hoplite', tier: "A", image: `${import.meta.env.BASE_URL}img/69_hoplite.png`, tags: [],},
  {id: 70, name_kor:"티키", name: 'tikitiki', tier: "C", image: `${import.meta.env.BASE_URL}img/70_tikitiki.png`, tags: [],},
  {id: 71, name_kor:"멘더", name: 'mender', tier: "S", image: `${import.meta.env.BASE_URL}img/71_mender.png`, tags: ["서폿", "멀티샷"],},
  {id: 72, name_kor:"광대", name: 'jester', tier: "D", image: `${import.meta.env.BASE_URL}img/72_jester.png`, tags: [],},
  {id: 73, name_kor:"건슬", name: 'gunslinger', tier: "C", image: `${import.meta.env.BASE_URL}img/73_gunslinger.png`, tags: [],},
  {id: 74, name_kor:"라바", name: 'lavamander', tier: "B", image: `${import.meta.env.BASE_URL}img/74_lavamander.png`, tags: [],},
  {id: 75, name_kor:"오브", name: 'abyssorb', tier: "SSS", image: `${import.meta.env.BASE_URL}img/75_abyssorb.png`, tags: ["이벤트","서폿"],},
  {id: 76, name_kor:"하운드", name: 'houndmaster', tier: "B", image: `${import.meta.env.BASE_URL}img/76_houndmaster.png`, tags: ["챔피언퀘스트"],},
  {id: 77, name_kor:"식충", name: 'carnivorous', tier: "A", image: `${import.meta.env.BASE_URL}img/77_carnivorous.png`, tags: ["멀티샷"],},
  {id: 78, name_kor:"킬러걸", name: 'killergirl', tier: "C", image: `${import.meta.env.BASE_URL}img/78_killergirl.png`, tags: [],},
  {id: 79, name_kor:"스톰", name: 'storm strider', tier: "C", image: `${import.meta.env.BASE_URL}img/79_storm_strider.png`, tags: [],},
  {id: 80, name_kor:"타임", name: 'time travler', tier: "C", image: `${import.meta.env.BASE_URL}img/80_time_travler.png`, tags: [],},
  {id: 81, name_kor:"바칼롯", name: 'sir barkalot', tier: "C", image: `${import.meta.env.BASE_URL}img/81_sir_barkalot.png`, tags: ["반사"],},
  {id: 82, name_kor:"고질", name: 'apex predator', tier: "A", image: `${import.meta.env.BASE_URL}img/82_apex_predator.png`, tags: ["2차 각성 체감↑"],},
  {id: 83, name_kor:"이터널", name: 'eternal', tier: "S", image: `${import.meta.env.BASE_URL}img/83_eternal.png`, tags: ["이벤트"],},
  {id: 84, name_kor:"마녀", name: 'shadow witch', tier: "B", image: `${import.meta.env.BASE_URL}img/84_shadow_witch.png`, tags: ["서폿"],},
  {id: 85, name_kor:"불냥", name: 'firefluff', tier: "B", image: `${import.meta.env.BASE_URL}img/85_firefluff.png`, tags: [],},
  {id: 86, name_kor:"개멬,메카어쌔", name: 'mech assassin', tier: "S", image: `${import.meta.env.BASE_URL}img/86_mech_assassin.png`, tags: ["보스사냥"],},
  {id: 87, name_kor:"골렘", name: 'a girl and her golem', tier: "SSS", image: `${import.meta.env.BASE_URL}img/87_a_girl_and_her_golem.png`, tags: ["현상금사냥꾼"],},
  {id: 88, name_kor:"커맨", name: 'commander vanellus', tier: "A", image: `${import.meta.env.BASE_URL}img/88_commander_vanellus.png`, tags: [],},
  {id: 89, name_kor:"슈히", name: 'superhero', tier: "SS", image: `${import.meta.env.BASE_URL}img/89_superhero.png`, tags: ["협동"],},
  {id: 90, name_kor:"미믹", name: 'mimic', tier: "S", image: `${import.meta.env.BASE_URL}img/90_mimic.png`, tags: ["게임플레이"],},
  {id: 91, name_kor:"빌런", name: 'supervilain', tier: "SS", image: `${import.meta.env.BASE_URL}img/91_supervilain.png`, tags: ["일일이벤트(생존)"],},
  {id: 92, name_kor:"지네", name: 'centipede', tier: "SSS", image: `${import.meta.env.BASE_URL}img/92_centipede.png`, tags: ["협동","보스사냥","일일이벤트(방어)"],},
  {id: 93, name_kor:"나블", name: 'nightblade', tier: "S", image: `${import.meta.env.BASE_URL}img/93_nightblade.png`, tags: [],},
  {id: 94, name_kor:"판다", name: 'panda', tier: "A", image: `${import.meta.env.BASE_URL}img/94_panda.png`, tags: [],},
];