// src/data.ts

// 1. 타입 내보내기 (export)
export type Tier = 'SSS' | 'SS' | 'S' | 'A' | 'B' | 'C' | 'D';

export interface Character {
  id: number;
  name: string;
  tier: Tier;
  image: string;
  tags: string[];
}

// 2. 캐릭터 데이터 내보내기 (export)
export const characterDB: Character[] = [
  {id: 1, name: 'elf archer', tier: "B", image: '/img/1_elf_archer.png', tags: [],},
  {id: 2, name: 'barbarian', tier: "B", image: '/img/2_barbarian.png', tags: ["반사", "2차 각성 체감↑"],},
  {id: 3, name: 'wizard', tier: "D", image: '/img/3_wizard.png', tags: [],},
  {id: 4, name: 'gorgon', tier: "SSS", image: '/img/4_gorgon.png', tags: ["멀티샷", "2차 각성 체감↑"],},
  {id: 5, name: 'angel', tier: "D", image: '/img/5_angel.png', tags: [],},
  {id: 6, name: 'voodoo', tier: "D", image: '/img/6_voodoo.png', tags: [],},
  {id: 7, name: 'spider queen', tier: "S", image: '/img/7_spider_queen.png', tags: ["2차 각성 체감↑"],},
  {id: 8, name: 'dragon knight', tier: "C", image: '/img/8_dragon_knight.png', tags: ["반사"],},
  {id: 9, name: 'druid', tier: "C", image: '/img/9_druid.png', tags: ["반사"],},
  {id: 10, name: 'crow', tier: "B", image: '/img/10_crow.png', tags: ["성소"],},
  {id: 11, name: 'imp master', tier: "A", image: '/img/11_imp_master.png', tags: ["챔피언퀘스트", "2차 각성 체감↑"],},
  {id: 12, name: 'frozen queen', tier: "D", image: '/img/12_frozen_queen.png', tags: [],},
  {id: 13, name: 'axe master', tier: "A", image: '/img/13_axe_master.png', tags: ["2차 각성 체감↑"],},
  {id: 14, name: 'rocky', tier: "D", image: '/img/14_rocky.png', tags: [],},
  {id: 15, name: 'sniper', tier: "S", image: '/img/15_sniper.png', tags: ["멀티샷(2각)", "2차 각성 체감↑"],},
  {id: 16, name: 'captain hook', tier: "A", image: '/img/16_captain_hook.png', tags: ["2차 각성 체감↑"],},
  {id: 17, name: 'lifestealer', tier: "SS", image: '/img/17_lifestealer.png', tags: ["멀티샷"],},
  {id: 18, name: 'berserker', tier: "C", image: '/img/18_berserker.png', tags: [],},
  {id: 19, name: 'raging orc', tier: "C", image: '/img/19_raging_orc.png', tags: [],},
  {id: 20, name: 'pirate', tier: "A", image: '/img/20_pirate.png', tags: ["멀티샷", "챔피언퀘스트", "2차 각성 체감↑"],},
  {id: 21, name: 'boom boom', tier: "B", image: '/img/21_boom_boom.png', tags: ["2차 각성 체감↑"],},
  {id: 22, name: 'grey wolf', tier: "C", image: '/img/22_grey_wolf.png', tags: ["해금조건"],},
  {id: 23, name: 'roller', tier: "D", image: '/img/23_roller.png', tags: ["해금조건"],},
  {id: 24, name: 'king', tier: "C", image: '/img/24_king.png', tags: ["반사"],},
  {id: 25, name: 'ninja', tier: "A", image: '/img/25_ninja.png', tags: ["멀티샷(2각)", "1차 각성 체감↑", "2차 각성 체감↑"],},
  {id: 26, name: 'engineer', tier: "C", image: '/img/26_engineer.png', tags: ["반사"],},
  {id: 27, name: 'hammerdin', tier: "C", image: '/img/27_hammerdin.png', tags: [],},
  {id: 28, name: 'renderman', tier: "D", image: '/img/28_renderman.png', tags: [],},
  {id: 29, name: 'phantom', tier: "C", image: '/img/29_phantom.png', tags: [],},
  {id: 30, name: 'gentleman', tier: "A", image: '/img/30_gentleman.png', tags: ["1차 각성 체감↑"],},
  {id: 31, name: 'vlad', tier: "C", image: '/img/31_vlad.png', tags: [],},
  {id: 32, name: 'mad doctor', tier: "D", image: '/img/32_mad_doctor.png', tags: [],},
  {id: 33, name: 'ancient one', tier: "S", image: '/img/33_ancient_one.png', tags: ["멀티샷"],},
  {id: 34, name: 'minotaur', tier: "D", image: '/img/34_minotaur.png', tags: [],},
  {id: 35, name: 'zeus', tier: "C", image: '/img/35_zeus.png', tags: [],},
  {id: 36, name: 'efreet', tier: "S", image: '/img/36_efreet.png', tags: ["1차 각성 체감↑", "2차 각성 체감↑"],},
  {id: 37, name: 'huntalisk', tier: "B", image: '/img/37_huntalisk.png', tags: ["1차 각성 체감↑"],},
  {id: 38, name: 'protector', tier: "C", image: '/img/38_protector.png', tags: [],},
  {id: 39, name: 'ape lord', tier: "S", image: '/img/39_ape_lord.png', tags: ["1차 각성 체감↑", "2차 각성 체감↑"],},
  {id: 40, name: 'mech', tier: "A", image: '/img/40_mech.png', tags: ["1차 각성 체감↑", "2차 각성 체감↑"],},
  {id: 41, name: 'the ripper', tier: "A", image: '/img/41_the_ripper.png', tags: ["1차 각성 체감↑","약화"],},
  {id: 42, name: 'thor', tier: "A", image: '/img/42_thor.png', tags: ["챔피언퀘스트", "성소"],},
  {id: 43, name: 'franky', tier: "SSS", image: '/img/43_franky.png', tags: ["1차 각성 체감↑","이벤트"],},
  {id: 44, name: 'grim reaper', tier: "C", image: '/img/44_grim_reaper.png', tags: [],},
  {id: 45, name: 'snowman', tier: "D", image: '/img/45_snowman.png', tags: [],},
  {id: 46, name: 'necromancer', tier: "C", image: '/img/46_necromancer.png', tags: [],},
  {id: 47, name: 'skull master', tier: "A", image: '/img/47_skull_master.png', tags: ["일일이벤트(방어)","2차 각성 체감↑"],},
  {id: 48, name: 'samurai', tier: "A", image: '/img/48_samurai.png', tags: ["성소","챌린지상점"],},
  {id: 49, name: 'trickster', tier: "A", image: '/img/49_trickster.png', tags: ["하드코어 협동", "성소"],},
  {id: 50, name: 'arachna', tier: "A", image: '/img/50_arachna.png', tags: [],},
  {id: 51, name: 'bunny', tier: "D", image: '/img/51_bunny.png', tags: ["이벤트"],},
  {id: 52, name: 'plague doctor', tier: "B", image: '/img/52_plague_doctor.png', tags: [],},
  {id: 53, name: 'void knight', tier: "A", image: '/img/53_void_knight.png', tags: ["약화"],},
  {id: 54, name: 'scarecrow', tier: "D", image: '/img/54_scarecrow.png', tags: [],},
  {id: 55, name: 'beetle', tier: "A", image: '/img/55_beetle.png', tags: [],},
  {id: 56, name: 'anubis', tier: "S", image: '/img/56_anubis.png', tags: ["1차 각성 체감↑"],},
  {id: 57, name: 'torment', tier: "S", image: '/img/57_torment.png', tags: ["공포"],},
  {id: 58, name: 'mutant turtle', tier: "SS", image: '/img/58_mutant_turtle.png', tags: ["반사","성소"],},
  {id: 59, name: 'mummy', tier: "A", image: '/img/59_mummy.png', tags: ["성소"],},
  {id: 60, name: 'turkey', tier: "D", image: '/img/60_turkey.png', tags: ["이벤트"],},
  {id: 61, name: 'plague rat', tier: "C", image: '/img/61_plague_rat.png', tags: [],},
  {id: 62, name: 'warebear', tier: "D", image: '/img/61_warebear.png', tags: [],},
  {id: 63, name: 'oni', tier: "C", image: '/img/63_oni.png', tags: ["이벤트"],},
  {id: 64, name: 'goblin engineer', tier: "B", image: '/img/64_goblin_engineer.png', tags: ["일일이벤트(방어)"],},
  {id: 65, name: 'succubus', tier: "S", image: '/img/65_succubus.png', tags: ["이벤트"],},
  {id: 66, name: 'ivy', tier: "C", image: '/img/66_ivy.png', tags: [],},
  {id: 67, name: 'leprechaun', tier: "SS", image: '/img/67_leprechaun.png', tags: ["이벤트","사냥","멀티샷","1차 각성 체감↑","2차 각성 체감↑"],},
  {id: 68, name: 'son wukong', tier: "C", image: '/img/68_son_wukong.png', tags: [],},
  {id: 69, name: 'hoplite', tier: "A", image: '/img/69_hoplite.png', tags: [],},
  {id: 70, name: 'tikitiki', tier: "C", image: '/img/70_tikitiki.png', tags: [],},
  {id: 71, name: 'mender', tier: "S", image: '/img/71_mender.png', tags: [],},
  {id: 72, name: 'jester', tier: "D", image: '/img/72_jester.png', tags: [],},
  {id: 73, name: 'gunslinger', tier: "C", image: '/img/73_gunslinger.png', tags: [],},
  {id: 74, name: 'lavamander', tier: "B", image: '/img/74_lavamander.png', tags: [],},
  {id: 75, name: 'abyssorb', tier: "SSS", image: '/img/75_abyssorb.png', tags: ["이벤트","공포"],},
  {id: 76, name: 'houndmaster', tier: "B", image: '/img/76_houndmaster.png', tags: ["챔피언퀘스트"],},
  {id: 77, name: 'carnivorous', tier: "A", image: '/img/77_carnivorous.png', tags: ["멀티샷"],},
  {id: 78, name: 'killergirl', tier: "C", image: '/img/78_killergirl.png', tags: [],},
  {id: 79, name: 'storm strider', tier: "C", image: '/img/79_storm_strider.png', tags: [],},
  {id: 80, name: 'time travler', tier: "C", image: '/img/80_time_travler.png', tags: [],},
  {id: 81, name: 'sir barkalot', tier: "C", image: '/img/81_sir_barkalot.png', tags: ["반사"],},
  {id: 82, name: 'apex predator', tier: "A", image: '/img/82_apex_predator.png', tags: ["2차 각성 체감↑"],},
  {id: 83, name: 'eternal', tier: "S", image: '/img/83_eternal.png', tags: ["이벤트"],},
  {id: 84, name: 'shadow witch', tier: "B", image: '/img/84_shadow_witch.png', tags: [],},
  {id: 85, name: 'firefluff', tier: "B", image: '/img/85_firefluff.png', tags: [],},
  {id: 86, name: 'mech assassin', tier: "S", image: '/img/86_mech_assassin.png', tags: ["보스사냥"],},
  {id: 87, name: 'a girl and her golem', tier: "SSS", image: '/img/87_a_girl_and_her_golem.png', tags: ["현상금사냥꾼"],},
  {id: 88, name: 'commander vanellus', tier: "A", image: '/img/88_commander_vanellus.png', tags: [],},
  {id: 89, name: 'superhero', tier: "SS", image: '/img/89_superhero.png', tags: ["협동"],},
  {id: 90, name: 'mimic', tier: "S", image: '/img/90_mimic.png', tags: ["해금조건"],},
  {id: 91, name: 'supervilain', tier: "SS", image: '/img/91_supervilain.png', tags: ["일일이벤트(생존)"],},
  {id: 92, name: 'centipede', tier: "SSS", image: '/img/92_centipede.png', tags: ["협동","보스사냥"],},
  {id: 93, name: 'nightblade', tier: "S", image: '/img/93_nightblade.png', tags: [],},
  {id: 94, name: 'panda', tier: "A", image: '/img/94_panda.png', tags: [],},
];